### PR TITLE
Decrypt NACL passwords on ext_pillar

### PR DESCRIPTION
**Pull request by epcim**
Adds the capability use the renderer for ext_pillars. The same as GPG is used - no rocket science here.

### CODE REVIEW

**Comment by steverweber** [comment]
I would like to see a migration to 'key_pub.' SealedBox
please see the current PR https://github.com/saltstack/salt/pull/41833

edit. oops disregard. this is using the render that is using nacl.dec_pub.

**Comment by yagnik** [comment]
@epcim should we instead open this against salt repo with changes from my branch ?

**Comment by epcim** [comment]
[**@yagnik**](https://github.com/yagnik) commented on [Jun 30, 2017, 2:02 PM GMT+2](https://github.com/yagnik/salt/pull/1#issuecomment-312249645 "2017-06-30T12:02:51Z - Replied by Github Reply Comments"):
> [@epcim](https://github.com/epcim) should we instead open this against salt repo with changes from my branch ?

Well I guess it has a reason besides nacl renderer provide the ext_pillar wrapper (this PR).

Recently saltstack#41833 was updated. Now from key_pub wash transformed to to sk, sk_file and pk, pk_file.. and now thre is secretbox_decrypt (we will encrypt data on ext_pillar with sk, and this render should decript them on salt-master). I don't see why/how to use the pub key part for this usecase.

So if you agree (let me know) I will update doc string in PR to contain `sk_file: /root/.nacl` instead of keyfile and I may give a try to write some test cases.

Will you rebase saltstack#41833?

**Comment by epcim** [comment]
Are you going to update the PR any time soon? (aka change from key_pub wash transformed to to sk, sk_file and pk, pk_file). 

I want to participate, as I have a use-case ext_pillar nacl. Run through regular NACL rendered the same as gpg does.

Thanks

**Comment by steverweber** [comment]
i'll try to get it resolved soon., if not this weekend; Monday.

**Comment by yagnik** [comment]
@epcim sorry was away for few days, will update this by tomorrow and rebase @steverweber work.

**Comment by steverweber** [comment]
my original branch was a mess it had some merges with upstream that were not fast forward ... also was failing some jenkins tests not sure why... so just started fresh. https://github.com/saltstack/salt/pull/42323

**Comment by epcim** [comment]
We should. I just was not abke to find proper branch. 
I also have no tests.  So I considered you may want to involve that in your renderer pr. 

P. 

30. 6. 2017 v 14:02, Yagnik <notifications@github.com>:

**Comment by yagnik** [comment]
@epcim do we still need this ? Sorry I was away for a little while so couldn't get to it earlier.

**Comment by epcim** [comment]
no ist already merged from pr directly to saltOn 10 Sep 2017 15:09, Yagnik <notifications@github.com> wrote:@epcim do we still need this ? Sorry I was away for a little while so couldn't get to it earlier.

**Pull request closed without merging**
